window.KIDSMATHS_AZURE_SPEECH_API_KEY = '2pKC3S0zFszIQsgRaC1efKvgGHMCnM8NsmtxsaVk0XmKflZEwGlQJQQJ99BHACmepeSXJ3w3AAAYACOGthHf';
window.KIDSMATHS_AZURE_TRANSLATOR_API_KEY = 'BXmqAF7llncoZff9mzSgh2EGoZ4BFMXuBkEmMoR74ymfiwwmVOhbJQQJ99BGACmepeSXJ3w3AAAbACOGmNx4';
window.KIDSMATHS_AZURE_REGION = 'uksouth';
window.KIDSMATHS_AZURE_URDU_TTS_VOICE = 'ur-PK-UzmaNeural';
window.KIDSMATHS_AZURE_ENGLISH_TTS_VOICE = 'en-GB-SoniaNeural';
